# Generated by Django 4.2.6 on 2024-03-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_language_language_language_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language',
        ),
    ]
