# Generated by Django 4.2.6 on 2024-03-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_language_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
