# Generated by Django 4.2.6 on 2024-03-12 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_rename_usercourse_usercource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCource',
            new_name='UserCourse',
        ),
    ]
