# Generated by Django 4.2.5 on 2024-04-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_theory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(null=True, upload_to='Media/featured_img')),
                ('featured_video', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('Deadline', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=100, null=True)),
                ('Certificate', models.CharField(max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.level')),
            ],
        ),
    ]
