# Generated by Django 4.2.5 on 2024-04-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_theorycourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theory',
            new_name='Categoriestheory',
        ),
    ]
