# Generated by Django 4.2.5 on 2024-04-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_courseresource_delete_theorycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriestheory'),
        ),
    ]
