# Generated by Django 4.2.5 on 2024-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_courseresource_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='file',
        ),
        migrations.AddField(
            model_name='courseresource',
            name='title',
            field=models.CharField(default='default_value_here', max_length=500),
        ),
        migrations.AddField(
            model_name='courseresource',
            name='files',
            field=models.ManyToManyField(related_name='course_resources', to='app.file'),
        ),
    ]
