# Generated by Django 4.2.5 on 2024-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_courseresource_files_courseresource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriestheory',
            name='title',
            field=models.CharField(default='default_value_here', max_length=500),
        ),
    ]
