# Generated by Django 4.2.5 on 2024-04-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_categoriestheory_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='course',
            new_name='courser',
        ),
    ]
